{
 "title": "Hello Postgres Data",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "What's the hourly availability?",
   "type": "timeseries",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('hour', request_time) as time,\n  count(*) as value,\n  status_code::text as metric\nFROM request\nGROUP BY time, metric\nORDER BY time"
    }
   ]
  },
  {
   "title": "What is the distribution of our users browsers?",
   "type": "piechart",
   "gridPos": { "h": 12, "w": 12, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "rawSql": "SELECT \n  user_agent as metric,\n  count(*) as value\nFROM request\nGROUP BY metric\nORDER BY value"
    }
   ]
  },
  {
   "title": "What is the rate of requests per minute?",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 12 },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('minute', request_time) as time,\n  count(*) as num_requests\nFROM request\nGROUP BY time\nORDER BY time"
    }
   ]
  },
  {
   "title": "What is the average response time?",
   "type": "timeseries",
   "gridPos": { "h": 14, "w": 24, "x": 0, "y": 26 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "rawSql": "SELECT \n  date_trunc('minute', request_time) as time,\n  avg(request_duration) as avg_duration\nFROM request\nGROUP BY time\nORDER BY time"
    }
   ]
  }
 ]
}